### ISSUE TITLE
写死在里面的ip地址115.239.134.167是什么

### ISSUE THREAD

**Issue by cheny1ran** [turingttc/newshanxun#1]
```
InetAddress local = InetAddress.getByName("115.239.134.167");
```

还有那个newdial.sinaapp.com是干啥用的
然后就是为什么username需要base64，password不需要？

问的问题可能比较蠢，还是希望得到解答！

**Comment by turingttc** [comment]
115.239.134.167这个是电信心跳服务器的地址。你抓下官方客户端的包就行了。
那个网址是我的服务器，请求数据用的。
username因为有特殊符号，在http传输的时候需要转码。密码的话直接从UI取过来就好了。

**Comment by cheny1ran** [comment]
谢谢回复！
